name: ci-deploying
run-name: ${{ github.actor }} is deploying GreenRute release
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: |
          corepack enable yarn
          yarn
          yarn build
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@greenrute.com
          if [ ! -d ".git" ]; then git init; fi
          git checkout -B gh-pages
          git add .
          git commit -am "Розгортання $(date +"%T %D")"
          git push -f git@github.com:newlancers/greenrute.git gh-pages:gh-
          cd ..
          rm -rf dist
