name: ci-deploying
run-name: ${{ github.actor }} is deploying GreenRute release
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install all dependencies
        run: |
          corepack enable yarn
          yarn

      - name: Build
        run: yarn build

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Розгортання: ({sha}) {msg}"
